kind: Template
apiVersion: v1
labels:
  app: cloud9
  template: cloud9
metadata:
  name: cloud9
  annotations:
    openshift.io/display-name: "Cloud9 v2 IDE"
    description: "Cloud9 v2 IDE.\n\nWARNING: Any data stored will be lost upon pod destruction."
    openshift.io/long-description: "Cloud9 IDE v2.\n\nWARNING: Any data stored will be lost upon pod destruction."
    tags: "ide,development,quickstart"
    iconClass: "fa fa-code"
    openshift.io/provider-display-name: "A-State Computer Science Department"
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: cloud9v2  
    spec:
      ports:
        - name: http
          port: 8181
          protocol: TCP
          targetPort: 8181
      selector:
        app: cloud9v2
  - apiVersion: v1
    kind: Route
    metadata:
      name: cloud9v2
    spec:
      tls:
        termination: edge
      to:
        kind: Service
        name: cloud9v2 
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: cloud9v2
    spec:
      replicas: 1
      selector:
        app: cloud9v2
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: cloud9v2
        spec:
          containers:
            - env:
              name: cloud9v2
              image: 'cloud9:v2'
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 11
                initialDelaySeconds: 80
                periodSeconds: 5
                successThreshold: 1
                tcpSocket:
                  port: 8181
                timeoutSeconds: 30
              ports:
                - containerPort: 8181
                  protocol: TCP
              volumeMounts:
                - mountPath: '/workspace'
                  name: cloud9v2-data
          restartPolicy: Always
          volumes:
            - name: cloud9v2-data
              persistentVolumeClaim:
                claimName: cloud9v2-data
      triggers:
        - type: ConfigChange
        - type: "ImageChange"
          imageChangeParams:
            automatic: true 
            from:
              kind: "ImageStreamTag"
              name: "cloud9:v2"
              namespace: "openshift"
            containerNames:
              - "cloud9v2"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: cloud9v2-data
      labels:
        app: cloud9v2
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
