apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: cloud9
objects:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: cloud9
    name: cloud9
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: cloud9
      weight: 100
