apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: cloud9
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: cloud9
    name: cloud9
  spec:
    ports:
    - name: 8181-tcp
      port: 8181
      protocol: TCP
      targetPort: 8181
    selector:
      deploymentconfig: cloud9
